services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5455:5455"
    environment:
      # Prefer overriding via .env at project root
      - AUTO_ATTACH_ON_REQUEST=${AUTO_ATTACH_ON_REQUEST:-1}
      - PYCHARM_REMOTE=${PYCHARM_REMOTE:-1}
      - PYCHARM_REMOTE_HOST=${PYCHARM_REMOTE_HOST:-host.docker.internal}
      - PYCHARM_REMOTE_PORT=${PYCHARM_REMOTE_PORT:-5454}
      - FLASK_ENV=${FLASK_ENV:-development}
    # On Linux, host.docker.internal may require extra host mapping
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount source for instant code changes without rebuilds
      - ./:/app
